channels:
  - conda-forge

dependencies:
  - python<=3.12
  - requests
  - geopandas
  - black
  - ipykernel
  - pandas
  - pyjwt
  - pytest
  - pytest-cov
  - netcdf4
  - rasterstats
  - rasterio
  - setuptools
  - xarray
  - rioxarray
  - twine