channels:
  - conda-forge

dependencies:
  - python==3.9
  - requests
  - geopandas==0.14
  - black
  - ipykernel
  - pandas==2.0
  - pyjwt
  - pytest
  - pytest-cov
  - netcdf4
  - rasterstats
  - rasterio
  - setuptools
  - xarray
  - rioxarray
  - twine