channels:
  - conda-forge
  - hdsr-mid
dependencies:
  - python<=3.12
  - requests
  - geopandas
  - pandas
  - jwt
  - black
  - pytest
  - pytest-cov
  - netcdf4
  - rasterstats
  - rasterio
  - setuptools
  - xarray
  - rioxarray
  - twine